### ISSUE TITLE
Can this project support H.264 MVC/BP/MP/HP??

### ISSUE THREAD

**Issue by Senwang98** [gergondet/ros_h264_streamer#1]
For some reasons of my work, i need to use H.264 decoder. However, I didn't know something about H.264, so I just want to know can this project support H.264 MVC/BP/MP/HP?

**Comment by gergondet** [comment]
Hi,

I haven't touched this project in a long time but I don't think the decoder is tied to the encoder profile.

**Comment by Senwang98** [comment]
Thanks for your reply, i think you are right

**Comment by gergondet** [comment]
Ok, I will close this issue now. Feel free to re-open if you encounter an issue with that.
